title: 蜗牛自由生活馆
description: 一个简单、自由的个人blog，用来分享投资、自由职业、学习笔记和胡思乱想。
lang: zh-CN
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title/

navigation:
  - name: 首页
    url: /
  - name: 日志
    url: /blog/
  - name: Gespenst Edge
    url: /gespenst_edge/
  - name: 关于
    url: /about/

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - venv/
  - __pycache__/
  - .Python
  - "*.pyc"
  - "*.pyo"
  - .gitignore
